version: '3.7'

services:

  cache.data:
    image: redis
    container_name: redisdb

  sql.data:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql.data

  air.api:
    image: ${DOCKER_REGISTRY-}air-api
    container_name: air.api
    build:
        context: .
        dockerfile: src/AirTravel.API/Dockerfile

  air.aggregator:
    image: ${DOCKER_REGISTRY-}air-aggregator
    container_name: air.aggregator
    build:
        context: .
        dockerfile: src/AirTravel.Aggregator/Dockerfile
  
  