version: '3.7'

services:
  postgres_exporter:
    container_name: exporter_container
    image: prometheuscommunity/postgres-exporter:v0.10.1

  postgres:
    container_name: postgres_container
    image: postgres:latest

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.2
    
  cache-data:
    image: redis
    container_name: redisdb_container

  # sql-data:
  #   image: mcr.microsoft.com/mssql/server:2019-latest
  #   container_name: sqldata

  air-api:
    image: ${DOCKER_REGISTRY-}air-api
    container_name: air_api_container
    build:
        context: .
        dockerfile: src/AirTravel.API/Dockerfile

  air-aggregator:
    image: ${DOCKER_REGISTRY-}air-aggregator
    container_name: air_aggregator_container
    build:
        context: .
        dockerfile: src/AirTravel.Aggregator/Dockerfile
  
  